name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Streamlit App
        uses: wei/curl@v1
        with:
          args: curl https://clasificador-nubes.streamlit.app/
